name: Khmer Cultural Heritage App
on:
  branch: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x  # Use the desired .NET version

    - name: Build and Publish
      run: dotnet publish -c Release -o out  # This assumes your project file is in the correct directory

    - name: Deploy to Railway
      uses: railwayapp/deploy@v2
      with:
        command: cp -r out $RAILWAY_BUILD_OUTPUT
